#! /usr/bin/env bash

__thispath="$(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null||echo $0)"
__dirname="$(dirname "$__thispath")"
__wd="$PWD"
__should_run=true
source "$__dirname/boot.sh"

usage() {
    cat <<EOM
Usage: $0 -c config_file [-g <config|slurm>] [-h]
Options:
    -c config file path
    -g generates a slurm file or example config file for your workflow without running it
    -h this helpful message
EOM
}

while getopts ":c:hd" opt; do
    case "$opt" in
    c ) 
        __config_filepath="$OPTARG"
        ;;
    h ) 
        usage 
        ;;
    d ) 
        log "Debugging: __should_run=false"
        __should_run=false
        ;;
    : )
        error "Invalid option: $OPTARG requires an argument"
        ;; 
    \? ) 
        usage 1>&2
        error "Invalid option: $OPTARG" 
        ;;
    esac
done; shift $((OPTIND-1))

source "$__dirname/configure.sh"

cd "$outputDirectory"

if [[ "$__should_run" = true ]]; then
    if [[ -x "$workflowFile" ]]; then
        log "Running workflow at $workflowFile"
        log "Logs will be written in $__log_file"
        {
            log "Starting Workflow at "$workflowFile""
            source "$workflowFile" 
            log "All Done! Cheers~" "$(clink)" 
        } &>> "$__log_file"
    else 
        error "Executable workflow file not found at $workflowFile" 
    fi
fi

cd "$__wd"